### ISSUE TITLE
커밋을 한글로 할까요 영어로 할까요?

### ISSUE THREAD

**Issue by snowflake-1117** [snowflake-1117/Android_Study#3]
영어가 보편적이니 그냥 영어를 쓰도록 할까요? 의견 주시기 바랍니다.

**Comment by lynring24** [comment]
English will be more helpful to our study

**Comment by lynring24** [comment]
진행하면서 영어로 커밋을 하는일이 생각보다 불편했습니다. 영어 / 한글 둘다 사용은 어떻습니까
